service: fssstepfunction
provider:
  name: aws
  runtime: dotnetcore3.1
  timeout: 25
  #vpc: ${self:custom.vpc.${opt:stage}}
  #stage: ${opt:stage}
  vpc: ${self:custom.vpc.development}
  stage: development
  region: eu-west-2
  environment:
    CONNECTION_STRING: Host=${ssm:/fss-public-api/${self:provider.stage}/postgres-hostname};Port=${ssm:/fss-public-api/${self:provider.stage}/postgres-port};Database=${ssm:/fss-public-api/${self:provider.stage}/postgres-database};Username=${ssm:/fss-public-api/${self:provider.stage}/postgres-username};Password=${ssm:/fss-public-api/${self:provider.stage}/postgres-password}
    NOTIFY_KEY: ${ssm:/fss-portal-api/${self:provider.stage}/notify-key}
    REVERIFICATION_FIRST_EMAIL_TEMPLATE: ${ssm:/fss-common/${self:provider.stage}/reverification-first-email-template}
    REVERIFICATION_SECOND_EMAIL_TEMPLATE: ${ssm:/fss-common/${self:provider.stage}/reverification-second-email-template}
    REVERIFICATION_THIRD_EMAIL_TEMPLATE: ${ssm:/fss-common/${self:provider.stage}/reverification-third-email-template}
    REVERIFICATION_PAUSE_EMAIL_TEMPLATE: ${ssm:/fss-common/${self:provider.stage}/reverification-pause-email-template}

package:
  # individually: true
  artifact: ./bin/release/netcoreapp3.1/fss-step-functions.zip

functions:
  firstStep:
    handler: CsharpHandlers::LbhFssStepFunction.Handler::FirstStep
  secondStep:
    handler: CsharpHandlers::LbhFssStepFunction.Handler::SecondStep
  thirdStep:
    handler: CsharpHandlers::LbhFssStepFunction.Handler::ThirdStep
  pauseStep:
    handler: CsharpHandlers::LbhFssStepFunction.Handler::PauseStep

stepFunctions:
  stateMachines:
    fssstepfunc1:
      events:
        - http:
            path: gofunction
            method: GET
        - schedule:
            rate: rate(24 hours)
            enabled: false
            input:
              organisationId: 3
              stageParams:
                stage: ${self:provider.stage}
      name: fssStateMachine-${self:provider.stage}
      definition:
        Comment: "An FSS step function deployed via serverless"
        StartAt: First_Step
        States:
          First_Step:
            Type: Task
            Resource:
              Fn::GetAtt: [ firstStep, Arn ]
            Next: Wait_1
          Wait_1:
            Type: Wait
            Seconds: 20
            Next: Choice_1
          Choice_1:
            Type: Choice
            Choices:
              - Variable: $.var
                NumericEquals: 0
                Next: Second_Step
              - Variable: $.var
                NumericEquals: 1
                Next: End_Step
          Second_Step:
            Type: Task
            Resource:
              Fn::GetAtt: [ secondStep, Arn ]
            Next: Wait_2
          Wait_2:
            Type: Wait
            Seconds: 20
            Next: Choice_2
          Choice_2:
            Type: Choice
            Choices:
              - Variable: $.var
                NumericEquals: 0
                Next: Third_Step
              - Variable: $.var
                NumericEquals: 1
                Next: End_Step
          Third_Step:
            Type: Task
            Resource:
              Fn::GetAtt: [ thirdStep, Arn ]
            Next: Wait_3
          Wait_3:
            Type: Wait
            Seconds: 20
            Next: Choice_3
          Choice_3:
            Type: Choice
            Choices:
              - Variable: $.var
                NumericEquals: 0
                Next: Pause_Step
              - Variable: $.var
                NumericEquals: 1
                Next: End_Step
          Pause_Step:
            Type: Task
            Resource:
              Fn::GetAtt: [ pauseStep, Arn ]
            Next: End_Step
          End_Step:
            End: true
      dependsOn: lambdaExecutionRole
      tags:
        Team: HackIt

resources:
  Resources:
    lambdaExecutionRole:
      Type: AWS::IAM::Role
      Properties:
        Path: /${self:service}/${self:provider.stage}/
        RoleName: ${self:service}-lambdaExecutionRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - arn:aws:iam::aws:policy/service-role/AWSLambdaVPCAccessExecutionRole
        Policies:
          - PolicyName: manageLogs
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - logs:CreateLogGroup
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource:
                    - 'Fn::Join':
                        - ':'
                        - - 'arn:aws:logs'
                          - Ref: 'AWS::Region'
                          - Ref: 'AWS::AccountId'
                          - 'log-group:/aws/lambda/*:*:*'
                - Effect: "Allow"
                  Action:
                    - "s3:PutObject"
                    - "s3:GetObject"
                  Resource:
                    Fn::Join:
                      - ""
                      - - "arn:aws:s3:::"
                        - "Ref": "ServerlessDeploymentBucket"
          - PolicyName: lambdaInvocation
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - "lambda:InvokeFunction"
                  Resource: "*"

custom:
  vpc:
    development:
      securityGroupIds:
        - sg-033babc9f5ce30345
      subnetIds:
        - subnet-0deabb5d8fb9c3446
        - subnet-000b89c249f12a8ad
    staging:
      securityGroupIds:
        - sg-04c73000bf97eae7e
      subnetIds:
        - subnet-06d3de1bd9181b0d7
        - subnet-0ed7d7713d1127656
    production:
      securityGroupIds:
        - sg-060458cddaaa2742a
      subnetIds:
        - subnet-01d3657f97a243261
        - subnet-0b7b8fea07efabf34

plugins:
  - serverless-step-functions
